### ISSUE TITLE
Update for 1.19.4

### ISSUE THREAD

**Issue by RoonMoonlight** [madjoel/waig#3]
Title says it all, but not sure if there is any breaking changes because of 1.19.4 update.

If it support, please mark the mod on CurseForge/Modrinth to be compatible with 1.19.4 release.

**Comment by madjoel** [comment]
Didn't realize that 1.19.4 was out already, thanks for the reminder.

I eventually will update the mod, meanwhile feel free to test if the 1.19.3 release works with 1.19.4. If there are no breaking changes, the mod is configured to work as is. Also feel free to post your results here 👍🏻

**Comment by madjoel** [comment]
Did the testing, and the 1.19.3 release of the mod works with 1.19.4. Updated all references.

**Comment by RoonMoonlight** [comment]
Yeah I have tested myself as well, it worked without any issues. Thank you for response!
