### ISSUE TITLE
[Feature(s)]: Further Customization

### ISSUE THREAD

**Issue by BioTechproject27** [madjoel/waig#5]
It would be cool if one could customize it even more, e.g. editing colors or adding additional data using [modern formatting](https://placeholders.pb4.eu/) by e.g. editing the looping string:
```
" . . . . . . . SW . . . . . . . W . . . . . . . NW . . . . . . . N . . . . . . . NE . . . . . . . E . . . . . . . SE . . . . . . . S"
(which is currently the default) turned into
" . . . . . . . SW . . . . . . . W . . . . . . . NW . . . . . . . <color:#AA0000>N</color> . . . . . . . NE . . . . . . . E . . . . . . . SE . . . . . . . S"
Which gives the N in north the dark red color, to clearly indicate when one is facing north-ish.
```

Or have
```
"<color:#555555> . . . . . . . <color:#AAAAAA>SW<color:#555555> . . . . . . . <color:#AAAAAA>W<color:#555555> . . . . . . . <color:#AAAAAA>NW<color:#555555> . . . . . . . <color:#AA0000>N<color:#555555> . . . . . . . <color:#AAAAAA>NE<color:#555555> . . . . . . . <color:#AAAAAA>E<color:#555555> . . . . . . . <color:#AAAAAA>SE<color:#555555> . . . . . . . <color:#AAAAAA>S"
```

For the darkmode users?
(#555555 is dark gray; #aaaaaa is light gray)

Maybe even add a little customizable border & background color & dimensions?
Maybe add a second, smaller string underneath, so one can have e.g. the time of day [%world:time%] or player ping [%player:ping_colored%] or maybe the players coordinates [%player:pos_x% %player:pos_y% %player:pos_z%; or maybe just %player:pos_x% %player:pos_z%] underneath?

It could maybe look like this(?):
```
Main string
" . . . . . . . SW . . . . . . . W . . . . . . . NW . . . . . . . N . . . . . . . NE . . . . . . . E . . . . . . . SE . . . . . . . S"
Sub string
"                                                                 %player:pos_x% %player:pos_z%                                                               
  %player:ping_colored%"
```

Maybe add different positions. E.g. at the top (which is the default currently), above/underneath crosshair, above hotbar?

**Comment by BioTechproject27** [comment]
Has this project been abandoned?

**Comment by madjoel** [comment]
Thank you for the suggestions. Most of them would add quite a lot of complexity, like the formatting for example, and will therefore not be implemented. Displaying the world time, ping, and player coordinates is out of scope of this mod and I would recommend [MiniHUD](https://www.curseforge.com/minecraft/mc-mods/minihud) or similar mods for that.

**Comment by BioTechproject27** [comment]
Yeah, mods like MiniHUD are not made to look good (at least not the current versions, they are working on a bigger project rn that may have that?)

And while yeah, they would be a bit more complicated, they would allow for much greater usability. Other formatting would just be easily included there
